version: '2'
services:
  web:
    restart: always
    build: ./web
    ports:
      - "8000:8000"
    links:
      - postgres:postgres
    volumes:
      - /usr/src/app/static
    depends_on:
      - postgres
    command: /usr/local/bin/gunicorn -w 2 -b :8000 app:app

  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    volumes:
      - /www/static
    volumes_from:
      - web
    links:
      - web:web

  data:
    image: postgres:latest
    volumes:
      - /var/lib/postgres

  postgres:
    restart: always
    image: postgres:latest
    environment:
      POSTGRES_USER: babylon
      POSTGRES_PASSWORD: babylon
    volumes_from:
      - data
    ports:
      - "5432:5432"

